/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Employee;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.controller.Controller;

/**
 *
 * @author Cartman
 */
public class FrmMain extends javax.swing.JFrame {

    private Employee employee;

    /**
     * Creates new form FrmMain
     */
    public FrmMain(Employee employee) {
        this.employee = employee;
        initComponents();
        setTitle(employee.getName() + " " + employee.getSurname());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        lblEmployee.setText(employee.getName() + " " + employee.getSurname());
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        menuClient = new javax.swing.JMenu();
        menuTreatment = new javax.swing.JMenu();
        menuAppointment = new javax.swing.JMenu();
        menuItemReservation = new javax.swing.JMenuItem();
        menuItemChangeReservation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 244, 236));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 43, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 100));

        lblEmployee.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(214, 52, 132));
        lblEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnCancel.setBackground(new java.awt.Color(214, 52, 132));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(64, 43, 58));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        menuClient.setText("Client");
        menuClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuClientMouseDragged(evt);
            }
        });
        menuClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuClientMouseEntered(evt);
            }
        });
        menuClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientActionPerformed(evt);
            }
        });
        menuBarMain.add(menuClient);

        menuTreatment.setText(" Treatment");
        menuTreatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTreatmentMouseClicked(evt);
            }
        });
        menuBarMain.add(menuTreatment);

        menuAppointment.setText(" Appointment");
        menuAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAppointmentMouseClicked(evt);
            }
        });

        menuItemReservation.setText("New reservation");
        menuItemReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemReservationMouseClicked(evt);
            }
        });
        menuItemReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReservationActionPerformed(evt);
            }
        });
        menuAppointment.add(menuItemReservation);

        menuItemChangeReservation.setText("Change reservation");
        menuItemChangeReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChangeReservationActionPerformed(evt);
            }
        });
        menuAppointment.add(menuItemChangeReservation);

        menuBarMain.add(menuAppointment);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientActionPerformed

    }//GEN-LAST:event_menuClientActionPerformed

    private void menuClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientMouseClicked
        try {
            new FrmClient().setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "New Client", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuClientMouseClicked

    private void menuClientMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClientMouseDragged

    private void menuClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientMouseEntered
    }//GEN-LAST:event_menuClientMouseEntered

    private void menuTreatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTreatmentMouseClicked
        try {
            new FrmTreatment().setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "New Treatment", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuTreatmentMouseClicked

    private void menuAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAppointmentMouseClicked

    }//GEN-LAST:event_menuAppointmentMouseClicked

    private void menuItemReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemReservationMouseClicked

    }//GEN-LAST:event_menuItemReservationMouseClicked

    private void menuItemReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReservationActionPerformed
        try {
            new FrmNewAppointment().setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "New Appointment", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemReservationActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //UNETI OPERACIJU ZA GASENJE SOFTVERA!!!!!!!!!!!!
        try {
            Controller.getInstance().logout();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void menuItemChangeReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChangeReservationActionPerformed
        try {
//            new FrmNewAppointment().setVisible(true);
            new FrmUpdateAppointment().setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "Change Appointment", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemChangeReservationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JMenu menuAppointment;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuClient;
    private javax.swing.JMenuItem menuItemChangeReservation;
    private javax.swing.JMenuItem menuItemReservation;
    private javax.swing.JMenu menuTreatment;
    // End of variables declaration//GEN-END:variables
}
